name: Build Static EXE with MinGW

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install MinGW
      run: |
        choco install mingw -y
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        
    - name: Compile
      run: |
        g++ --version
        g++ -static -static-libgcc -static-libstdc++ -O2 -o GDScratchRenderer.exe main.cpp -lgdi32 -lcomctl32 -Wl,-subsystem,windows
        
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: GDScratchRenderer
        path: GDScratchRenderer.exe
